---
name: Release

# For some reason yamllint thinks these should be truthy
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: durandj/journal

jobs:
  Release:
    runs-on: ubuntu-latest
    environment: release

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - name: pnpm
        run: |
          corepack enable
          pnpm install

      - name: Build
        run: pnpm run build

      - uses: pre-commit/action@v3.0.1

      - name: Build journal-solid container image
        uses: docker/build-push-action@v6.19.1
        with:
          push: false
          file: packages/journal-solid/Dockerfile

      - name: Tag new version
        id: semrel
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Log in to the container registry
        if: steps.semrel.outputs.version != ''
        uses: docker/login-action@v3.7.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            latest

      - name: Build journal-solid container image
        if: steps.semrel.outputs.version != ''
        id: push
        uses: docker/build-push-action@v6.19.1
        with:
          push: true
          file: packages/journal-solid/Dockerfile
          # yamllint disable-line rule:line-length
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.semrel.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        if: steps.semrel.outputs.version != ''
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
